### ISSUE TITLE
能否在所有应用中启用智能助理，并赋予其执行代码的能力？

### ISSUE THREAD

**Issue by NekoMirra** [thunlp/ProactiveAgent#5]
如题，目前基本只会要求不停的搜索，太笨了（）

**Comment by SummerFall1819** [comment]
1.Enable Active agent in all applications.
1.在所有应用中启用智能助理

Active agent relies heavily on the environment collected by our program, and we currently use Activity Watcher as one approach, collecting only chrome information and vs-code workspace information and aiming at providing assistance at coding and writing scenes. Though we also collect keyboard and mouse events, they suffer greatly from the noise(E.g. deletion, hot-keys, and auto-implement when in editors.) Enable it in all applications requires universal information that could generally apply(or if your prefer, we could use screenshots as environment information). Our next major update focuses on extensive listener settings and tool call settings so that you may contribute in certain application at that time.
智能助理依赖于我们程序所采集的环境信息，我们当前采用的方式是使用 Activity Watcher，采集浏览器的信息和 vscode 的工作区信息，并关注在编程和写作场景提供帮助。尽管我们也采集了键鼠信息，但是键鼠信息受噪音影响很大(删除文本，热键使用，在使用编辑器的时候自动补全无法捕获等)，在所有应用中启用智能助理需要更通用的信息(或者我们也可以采集屏幕截图作为环境信息 :> )。 我们的下一次大更新将专注于设计更易拓展的监听设置和工具调用设置，您可以在那个时候协助贡献特定应用。

2.Grant ability to execute code.
2.赋予执行代码的能力

We could grant the agent with the ability to execute code(like bash, psl, or even generate python code to execute), however we could't guarantee the code agent actually generated. Agent may actually generate harmful codes that would lead to unexpected results. That's why we currently only allow agent to rename file, rather than let it access to the system commands. Once we support linux as described in issue #1, you may want to try unsafe execution in a sandbox.
我们可以给智能体提供执行代码的能力(比如 Bash 脚本， powershell 脚本甚至直接执行 python 代码), 然而我们并不能保证智能体实际生成的代码内容。智能体可能会生成有害内容，产生非预期的结果。这就是为什么我们只允许智能体重命名脚本，而非直接开放控制台指令。当我们支持 linux 的时候，你可以在一个沙盒环境中执行不安全的代码运行。

**Comment by luyaxi** [comment]
受限于精力，我们暂时没有集成更多工具到agent的计划。

我们十分欢迎社区人员提交和贡献代码。相关的文档会在之后放出

**Comment by NekoMirra** [comment]
> 1.Enable Active agent in all applications. 1.在所有应用中启用智能助理
> 
> Active agent relies heavily on the environment collected by our program, and we currently use Activity Watcher as one approach, collecting only chrome information and vs-code workspace information and aiming at providing assistance at coding and writing scenes. Though we also collect keyboard and mouse events, they suffer greatly from the noise(E.g. deletion, hot-keys, and auto-implement when in editors.) Enable it in all applications requires universal information that could generally apply(or if your prefer, we could use screenshots as environment information). Our next major update focuses on extensive listener settings and tool call settings so that you may contribute in certain application at that time. 智能助理依赖于我们程序所采集的环境信息，我们当前采用的方式是使用 Activity Watcher，采集浏览器的信息和 vscode 的工作区信息，并关注在编程和写作场景提供帮助。尽管我们也采集了键鼠信息，但是键鼠信息受噪音影响很大(删除文本，热键使用，在使用编辑器的时候自动补全无法捕获等)，在所有应用中启用智能助理需要更通用的信息(或者我们也可以采集屏幕截图作为环境信息 :> )。 我们的下一次大更新将专注于设计更易拓展的监听设置和工具调用设置，您可以在那个时候协助贡献特定应用。
> 
> 2.Grant ability to execute code. 2.赋予执行代码的能力
> 
> We could grant the agent with the ability to execute code(like bash, psl, or even generate python code to execute), however we could't guarantee the code agent actually generated. Agent may actually generate harmful codes that would lead to unexpected results. That's why we currently only allow agent to rename file, rather than let it access to the system commands. Once we support linux as described in issue #1, you may want to try unsafe execution in a sandbox. 我们可以给智能体提供执行代码的能力(比如 Bash 脚本， powershell 脚本甚至直接执行 python 代码), 然而我们并不能保证智能体实际生成的代码内容。智能体可能会生成有害内容，产生非预期的结果。这就是为什么我们只允许智能体重命名脚本，而非直接开放控制台指令。当我们支持 linux 的时候，你可以在一个沙盒环境中执行不安全的代码运行。

感谢解答，顺便请问下，在readme中PC微信场景的示例是如何实现的呢？

**Comment by luyaxi** [comment]
> > 1.Enable Active agent in all applications. 1.在所有应用中启用智能助理
> > Active agent relies heavily on the environment collected by our program, and we currently use Activity Watcher as one approach, collecting only chrome information and vs-code workspace information and aiming at providing assistance at coding and writing scenes. Though we also collect keyboard and mouse events, they suffer greatly from the noise(E.g. deletion, hot-keys, and auto-implement when in editors.) Enable it in all applications requires universal information that could generally apply(or if your prefer, we could use screenshots as environment information). Our next major update focuses on extensive listener settings and tool call settings so that you may contribute in certain application at that time. 智能助理依赖于我们程序所采集的环境信息，我们当前采用的方式是使用 Activity Watcher，采集浏览器的信息和 vscode 的工作区信息，并关注在编程和写作场景提供帮助。尽管我们也采集了键鼠信息，但是键鼠信息受噪音影响很大(删除文本，热键使用，在使用编辑器的时候自动补全无法捕获等)，在所有应用中启用智能助理需要更通用的信息(或者我们也可以采集屏幕截图作为环境信息 :> )。 我们的下一次大更新将专注于设计更易拓展的监听设置和工具调用设置，您可以在那个时候协助贡献特定应用。
> > 2.Grant ability to execute code. 2.赋予执行代码的能力
> > We could grant the agent with the ability to execute code(like bash, psl, or even generate python code to execute), however we could't guarantee the code agent actually generated. Agent may actually generate harmful codes that would lead to unexpected results. That's why we currently only allow agent to rename file, rather than let it access to the system commands. Once we support linux as described in issue #1, you may want to try unsafe execution in a sandbox. 我们可以给智能体提供执行代码的能力(比如 Bash 脚本， powershell 脚本甚至直接执行 python 代码), 然而我们并不能保证智能体实际生成的代码内容。智能体可能会生成有害内容，产生非预期的结果。这就是为什么我们只允许智能体重命名脚本，而非直接开放控制台指令。当我们支持 linux 的时候，你可以在一个沙盒环境中执行不安全的代码运行。
> 
> 感谢解答，顺便请问下，在readme中PC微信场景的示例是如何实现的呢？

修改监听路径为微信的下载文件夹即可实现

**Comment by NekoMirra** [comment]
> 1.Enable Active agent in all applications. 1.在所有应用中启用智能助理
> 
> Active agent relies heavily on the environment collected by our program, and we currently use Activity Watcher as one approach, collecting only chrome information and vs-code workspace information and aiming at providing assistance at coding and writing scenes. Though we also collect keyboard and mouse events, they suffer greatly from the noise(E.g. deletion, hot-keys, and auto-implement when in editors.) Enable it in all applications requires universal information that could generally apply(or if your prefer, we could use screenshots as environment information). Our next major update focuses on extensive listener settings and tool call settings so that you may contribute in certain application at that time. 智能助理依赖于我们程序所采集的环境信息，我们当前采用的方式是使用 Activity Watcher，采集浏览器的信息和 vscode 的工作区信息，并关注在编程和写作场景提供帮助。尽管我们也采集了键鼠信息，但是键鼠信息受噪音影响很大(删除文本，热键使用，在使用编辑器的时候自动补全无法捕获等)，在所有应用中启用智能助理需要更通用的信息(或者我们也可以采集屏幕截图作为环境信息 :> )。 我们的下一次大更新将专注于设计更易拓展的监听设置和工具调用设置，您可以在那个时候协助贡献特定应用。
> 
> 2.Grant ability to execute code. 2.赋予执行代码的能力
> 
> We could grant the agent with the ability to execute code(like bash, psl, or even generate python code to execute), however we could't guarantee the code agent actually generated. Agent may actually generate harmful codes that would lead to unexpected results. That's why we currently only allow agent to rename file, rather than let it access to the system commands. Once we support linux as described in issue #1, you may want to try unsafe execution in a sandbox. 我们可以给智能体提供执行代码的能力(比如 Bash 脚本， powershell 脚本甚至直接执行 python 代码), 然而我们并不能保证智能体实际生成的代码内容。智能体可能会生成有害内容，产生非预期的结果。这就是为什么我们只允许智能体重命名脚本，而非直接开放控制台指令。当我们支持 linux 的时候，你可以在一个沙盒环境中执行不安全的代码运行。
( •̀ ω •́ )✧
这里也推荐关注一个名为Openinterpreter的项目，尽管她仍然是一个被动代理，但是对计算机的控制的实现可以借鉴（？
